# Generated by Django 5.2.6 on 2025-09-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['price'], 'verbose_name': 'table'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='print',
            new_name='price',
        ),
    ]
