# Generated by Django 5.2.6 on 2025-09-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_products_options_rename_print_products_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-price'], 'verbose_name': 'table'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('category_1', '1'), ('category_2', '2')], null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
